const $ = id => document.getElementById(id);
const state = {market:null, products:[], fundamentals:{}, filtered:[], sector:'全部', view:'cards', detail:null, frame:'D', strategyFrame:'D'};
const sectors=['全部','有色','贵金属','黑色','能化','农产品','金融','其他'];
const fmt=(v,d)=>v==null||Number.isNaN(+v)?'—':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:d??(Math.abs(+v)<100?2:0),maximumFractionDigits:d??(Math.abs(+v)<100?2:0)});
const signed=(v,d=2)=>`${+v>=0?'+':''}${fmt(v,d)}`;
const cls=t=>t==='up'?'tone-up':t==='down'?'tone-down':'tone-neutral';
const dl=pairs=>pairs.map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');
const range=v=>`${fmt(v?.[0])} — ${fmt(v?.[1])}`;

const cssv=(n,f)=>{const v=getComputedStyle(document.body).getPropertyValue(n).trim();return v||f};
function applyTheme(t){document.body.classList.toggle('theme-journal',t==='journal');localStorage.setItem('yafco-theme',t);const b=$('themeToggle');if(b)b.textContent=t==='journal'?'🌊 深渊风':'🌿 手账风';if(state.detail)renderChart()}
function initTheme(){const q=new URLSearchParams(location.search).get('theme');applyTheme(q==='journal'||q==='abyss'?q:(localStorage.getItem('yafco-theme')||'abyss'));const b=$('themeToggle');if(b)b.addEventListener('click',e=>{e.preventDefault();applyTheme(document.body.classList.contains('theme-journal')?'abyss':'journal')})}

async function fetchJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function refreshLive(){if(!booted||!window.YAFCOAccess?.allowed()||!state.market)return;try{const next=await fetchJSON(`data/market.json?t=${Date.now()}`);if(!next?.updated_at||next.updated_at===state.market.updated_at)return;state.market=next;state.products=next.products||[];renderMeta();renderRadar();applyFilters();renderDailyPicks();if(state.detail?.product?.product){const symbol=state.detail.product.product;state.detail=await fetchJSON(`data/symbols/${symbol}.json?t=${Date.now()}`);renderDetail(state.detail)}}catch(e){console.warn('live snapshot refresh skipped',e)}}
async function init(){try{state.market=await fetchJSON(`data/market.json?t=${Date.now()}`);state.products=state.market.products||[];try{const f=await fetchJSON(`data/fundamentals.json?t=${Date.now()}`);state.fundamentals=Object.fromEntries((f.products||[]).map(x=>[x.symbol,x]))}catch(e){console.warn('fundamentals unavailable',e)}renderMeta();renderFilters();renderRadar();applyFilters();bind();renderDailyPicks();setTimeout(()=>$('loadingScreen').classList.add('done'),420);const hash=location.hash.match(/symbol=([A-Z0-9]+)/i);if(hash)openDetail(hash[1].toUpperCase(),false)}catch(e){$('loadingScreen').querySelector('span').textContent=`数据链路失败：${e.message}`;toast(e.message)}}
function bind(){$('searchInput').addEventListener('input',applyFilters);$('sortSelect').addEventListener('change',applyFilters);$('sectorFilters').addEventListener('click',e=>{if(!e.target.dataset.sector)return;state.sector=e.target.dataset.sector;renderFilters();applyFilters()});document.querySelector('.scanner-summary div').addEventListener('click',e=>{if(!e.target.dataset.view)return;state.view=e.target.dataset.view;document.querySelectorAll('.scanner-summary button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));renderProducts()});$('productGrid').addEventListener('click',e=>{const card=e.target.closest('[data-symbol]');if(card)openDetail(card.dataset.symbol)});$('productTable').addEventListener('click',e=>{const row=e.target.closest('[data-symbol]');if(row)openDetail(row.dataset.symbol)});const dp=$('dailyPicks');if(dp)dp.addEventListener('click',e=>{const it=e.target.closest('[data-symbol]');if(it)openDetail(it.dataset.symbol)});$('bullRank').addEventListener('click',rankClick);$('bearRank').addEventListener('click',rankClick);$('closeDetail').addEventListener('click',()=>{location.hash='detail';$('detailShell').classList.add('hidden');$('detailEmpty').classList.remove('hidden')});$('chartTabs').addEventListener('click',e=>{if(!e.target.dataset.frame)return;state.frame=e.target.dataset.frame;document.querySelectorAll('#chartTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame===state.frame));renderChart()});$('strategyTabs').addEventListener('click',e=>{if(!e.target.dataset.frame)return;state.strategyFrame=e.target.dataset.frame;document.querySelectorAll('#strategyTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame===state.strategyFrame));renderStrategy()});$('coverRandom').addEventListener('click',()=>{const p=state.products[Math.floor(Math.random()*state.products.length)];openDetail(p.symbol)});}
function renderDailyPicks(){const el=$('dailyPicks');if(!el||!state.products.length)return;const ps=state.products.filter(p=>p.last!=null&&p.score!=null);
const strong=[...ps].sort((a,b)=>b.score-a.score).slice(0,3),weak=[...ps].sort((a,b)=>a.score-b.score).slice(0,3);
const near=ps.map(p=>{const r=(p.resistance||[])[0],s=(p.support||[])[0];let best=null;
if(r&&r>p.last)best={d:(r-p.last)/p.last,side:'压力',price:r};
if(s&&s<p.last){const ds=(p.last-s)/p.last;if(!best||ds<best.d)best={d:ds,side:'支撑',price:s}}
return{p,best}}).filter(x=>x.best&&Math.abs(x.p.score)<3.5).sort((a,b)=>a.best.d-b.best.d).slice(0,3);
const item=(p,note)=>{const tone=p.score>0?'tone-up':p.score<0?'tone-down':'tone-neutral';return`<div class="pick-item" data-symbol="${p.symbol}"><b>${p.name} ${p.symbol}</b><span class="pick-score ${tone}">${signed(p.score)}</span><small>${note}</small></div>`};
el.innerHTML='<div class="picks-col"><header><span>共振最强</span><b>STRONG</b></header>'+strong.map(p=>item(p,`${p.ari.split('·')[0].trim()} · ${p.change_pct!=null?signed(p.change_pct)+'%':''}`)).join('')+'</div>'
+'<div class="picks-col"><header><span>共振最弱</span><b>WEAK</b></header>'+weak.map(p=>item(p,`${p.ari.split('·')[0].trim()} · ${p.change_pct!=null?signed(p.change_pct)+'%':''}`)).join('')+'</div>'
+'<div class="picks-col"><header><span>待突破 · 区间边界</span><b>BREAKOUT</b></header>'+near.map(x=>item(x.p,`贴近${x.best.side} ${fmt(x.best.price)} · 距离 ${(x.best.d*100).toFixed(2)}%`)).join('')+'</div>'}
function rankClick(e){const item=e.target.closest('[data-symbol]');if(item)openDetail(item.dataset.symbol)}
function renderMeta(){const m=state.market,age=Math.max(0,Date.now()-new Date(m.updated_at).getTime()),mins=Math.floor(age/60000),delay=mins<=3?'实时':mins<=20?`延迟 ${mins} 分钟`:`数据滞后 ${mins} 分钟`;$('coverCount').textContent=m.total_published;$('coverFresh').textContent=`${m.fresh} FRESH / ${m.stale} STALE`;$('coverStatus').textContent=`DATA LINK · ${m.total_published}/${m.total_supported}`;$('headerUpdated').textContent=delay;$('headerUpdated').classList.toggle('quality-warning',mins>20);$('footerUpdated').textContent=`SNAPSHOT ${m.updated_at.slice(0,16).replace('T',' ')}`;$('buildState').innerHTML=`${delay}<br>FRESH ${m.fresh} / STALE ${m.stale}`;}
function renderFilters(){$('sectorFilters').innerHTML=sectors.map(s=>`<button data-sector="${s}" class="${s===state.sector?'active':''}">${s}</button>`).join('')}
function renderRadar(){const sorted=[...state.products].sort((a,b)=>b.score-a.score);renderRank('bullRank',sorted.slice(0,5));renderRank('bearRank',sorted.slice(-5).reverse());const avg=state.products.reduce((s,p)=>s+(+p.score||0),0)/Math.max(1,state.products.length);$('marketBalance').textContent=signed(avg,2);$('marketBalance').className=cls(avg>.4?'up':avg<-.4?'down':'neutral');$('marketBalanceText').textContent=avg>.4?'多头结构占优':avg<-.4?'空头结构占优':'多空结构均衡';const counts={};state.products.forEach(p=>counts[p.sector]=(counts[p.sector]||0)+1);const positions=[[19,25],[72,18],[80,62],[30,75],[55,82],[12,58],[58,12]];$('sectorDots').innerHTML=Object.entries(counts).map(([s,n],i)=>`<i class="sector-dot" style="left:${positions[i%positions.length][0]}%;top:${positions[i%positions.length][1]}%"><span>${s} ${n}</span></i>`).join('')}
function renderRank(id,items){$(id).innerHTML=items.map((p,i)=>`<div class="rank-item" data-symbol="${p.symbol}"><i>0${i+1}</i><div><b>${p.name} ${p.symbol}</b><small>${p.ari} · ${p.macd}</small></div><span class="${cls(p.tone)}">${signed(p.score)}</span></div>`).join('')}
function applyFilters(){const q=$('searchInput')?.value.trim().toLowerCase()||'';let items=state.products.filter(p=>(state.sector==='全部'||p.sector===state.sector)&&(!q||`${p.name} ${p.symbol} ${p.sector} ${p.exchange}`.toLowerCase().includes(q)));const sort=$('sortSelect')?.value||'score-desc';items.sort((a,b)=>sort==='score-desc'?b.score-a.score:sort==='score-asc'?a.score-b.score:sort==='change-desc'?(b.change_pct||0)-(a.change_pct||0):sort==='change-asc'?(a.change_pct||0)-(b.change_pct||0):a.symbol.localeCompare(b.symbol));state.filtered=items;$('resultCount').textContent=`显示 ${items.length} / ${state.products.length} 个航行目标`;renderProducts()}
function renderProducts(){const cards=state.filtered.map(p=>`<article class="product-card ${p.tone}" data-symbol="${p.symbol}"><header><b>${p.symbol}</b><span>${p.exchange}</span></header><h3>${p.name}</h3><div class="price"><b>${fmt(p.last)}</b><span class="${p.change_pct>0?'tone-up':p.change_pct<0?'tone-down':'tone-neutral'}">${signed(p.change_pct||0,2)}%</span></div><div class="data-badge ${p.data_mode==='完整多周期'?'official':'proxy'}">${p.data_mode||'数据状态未知'}</div><footer><span>${p.ari.split('·')[0].trim()} · ${p.sector}${p.stale?' · STALE':''}${p.vol_regime?` · σ${Math.round(p.vol20)}% ${p.vol_regime}`:''}</span><b class="${cls(p.tone)}">${signed(p.score)}</b></footer></article>`).join('');$('productGrid').innerHTML=cards;$('productGrid').classList.toggle('hidden',state.view!=='cards');const rows=state.filtered.map(p=>`<div class="table-row" data-symbol="${p.symbol}"><b>${p.symbol}</b><span>${p.name}</span><span>${p.sector}</span><span>${fmt(p.last)}</span><span class="${p.change_pct>0?'tone-up':'tone-down'}">${signed(p.change_pct||0,2)}%</span><span>${p.ari}</span><b class="${cls(p.tone)}">${signed(p.score)}</b></div>`).join('');$('productTable').innerHTML=`<div class="table-row table-head"><b>代码</b><span>品种</span><span>板块</span><span>现价</span><span>涨跌</span><span>Ari环境</span><b>共振</b></div>${rows}`;$('productTable').classList.toggle('hidden',state.view!=='table')}
async function openDetail(symbol,scroll=true){$('detailEmpty').classList.remove('hidden');$('detailEmpty').innerHTML=`<span>DESCENDING TO ${symbol}</span><h2>读取深层结构档案</h2><p>正在建立四框架数据链路……</p>`;if(scroll)$('detail').scrollIntoView({behavior:'smooth'});try{const d=await fetchJSON(`data/symbols/${symbol}.json?t=${Date.now()}`);state.detail=d;state.frame='D';state.strategyFrame='D';document.querySelectorAll('#chartTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame==='D'));document.querySelectorAll('#strategyTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame==='D'));renderDetail(d);$('detailEmpty').classList.add('hidden');$('detailShell').classList.remove('hidden');history.replaceState(null,'',`#detail?symbol=${symbol}`)}catch(e){$('detailEmpty').innerHTML=`<span>DATA LINK INTERRUPTED</span><h2>${symbol} 档案读取失败</h2><p>${e.message}</p>`}}
function renderDetail(d){const p=d.product,q=d.quote,f=d.frameworks,dec=d.decision,m=d.market,analysisAt=d.analysis_updated_at?new Date(d.analysis_updated_at).toLocaleString('zh-CN',{hour12:false}):'未知';$('detailSector').textContent=`${p.sector} / ${p.exch_cn}`;$('detailContract').textContent=String(q.symbol).toUpperCase();$('detailName').textContent=`${p.name} ${p.product}`;$('detailSource').textContent=`报价 ${q.time||'—'} · 策略计算 ${analysisAt} · ${d.snapshot_status==='stale'?'沿用最近成功快照':'数据链路正常'}`;$('detailPrice').textContent=fmt(q.last);$('detailChange').textContent=`${signed(q.change_pct,2)}%`;$('detailChange').className=q.change_pct>0?'tone-up':q.change_pct<0?'tone-down':'tone-neutral';$('detailScore').textContent=signed(dec.score);$('detailScore').className=cls(dec.tone);$('detailBias').textContent=dec.bias;$('detailBias').className=cls(dec.tone);renderFrameworks(f);renderStrategy();renderFundamental(p.product);$('truthNote').textContent=m.seat_note;$('truthOi').textContent=fmt(m.open_interest);$('truthVolume').textContent=fmt(m.volume);renderChart()}
function renderFundamental(symbol){const card=$('fundamentalCard'),f=state.fundamentals[String(symbol).toUpperCase()];if(!f?.covered){card.classList.add('hidden');return}card.classList.remove('hidden');const link=$('fundamentalLink');if(f.kind==='market_snapshot'){const inv=f.inventory||{},sp=f.spread||{};$('fundamentalTitle').textContent='库存与期限结构';$('fundamentalThesis').textContent=f.summary||'基础实物面快照';const move=inv.latest==null?'未匹配到可靠库存口径':inv.stale?'库存数据滞后':`${inv.comparison} ${inv.change_pct>0?'↑':inv.change_pct<0?'↓':'→'}${fmt(Math.abs(inv.change_pct),1)}%`;const invRow=`<div class="fundamental-metric"><div><b>${inv.name||'库存'}</b><small>${inv.source||'知几·料'} · ${inv.end||'—'}</small></div><span>${inv.latest==null?'—':`${fmt(inv.latest)} ${inv.unit||''}`}<small>${move}</small></span></div>`;const spreadRow=`<div class="fundamental-metric"><div><b>主力－下一活跃</b><small>${sp.near_symbol||'—'} / ${sp.far_symbol||'—'}</small></div><span class="${sp.value>0?'tone-up':sp.value<0?'tone-down':'tone-neutral'}">${sp.value==null?'—':signed(sp.value)}<small>${sp.structure||sp.status||'月差待更新'}</small></span></div>`;$('fundamentalMetrics').innerHTML=invRow+spreadRow;link.classList.add('hidden');return}$('fundamentalTitle').textContent='基本面主要矛盾';$('fundamentalThesis').textContent=f.contradiction;$('fundamentalMetrics').innerHTML=(f.metrics||[]).slice(0,3).map(m=>{const move=m.change_pct==null?'读取失败':m.stale?'数据滞后':`${m.comparison} ${m.change_pct>0?'↑':m.change_pct<0?'↓':'→'}${fmt(Math.abs(m.change_pct),1)}%`;return`<div class="fundamental-metric"><div><b>${m.name}</b><small>${m.why}</small></div><span>${fmt(m.latest)} ${m.unit}<small>${move} · ${m.end||'—'}</small></span></div>`}).join('');link.href=f.library_url;link.classList.remove('hidden')}
function renderFrameworks(f){$('ariTone').textContent=f.ari.environment;$('ariTone').className=cls(f.ari.tone);$('ariScore').textContent=signed(f.ari.score);$('ariScore').className=cls(f.ari.tone);$('ariDetail').innerHTML=dl([['多空线',`${fmt(f.ari.line)} · ${f.ari.line_relation}`],['动量',f.ari.momentum],['RSI W/D/60/15',`${fmt(f.ari.rsiW,1)} / ${fmt(f.ari.rsiD,1)} / ${fmt(f.ari.rsi60,1)} / ${fmt(f.ari.rsi15,1)}`]]);$('chanTone').textContent=f.chan.signal;$('chanTone').className=cls(f.chan.tone);$('chanScore').textContent=signed(f.chan.score);$('chanScore').className=cls(f.chan.tone);$('chanDetail').innerHTML=dl([['日线末笔',f.chan.last_pen],['结构',f.chan.structure],['中枢',f.chan.zone?`${fmt(f.chan.zone.low)} — ${fmt(f.chan.zone.high)}`:'未形成稳定中枢'],['背驰',f.chan.divergence],['周 / 60 / 15',`${f.chan.frames.W.last_pen} / ${f.chan.frames['60'].last_pen} / ${f.chan.frames['15'].last_pen}`]]);$('macdTone').textContent=f.macd.summary;$('macdTone').className=cls(f.macd.tone);$('macdScore').textContent=signed(f.macd.score);$('macdScore').className=cls(f.macd.tone);$('macdDetail').innerHTML=dl(f.macd.details.map(x=>[x.frame,`${x.state} · 柱${x.direction} (${signed(x.hist,1)})`]));$('gannTone').textContent=f.gann.line_relation;$('gannTone').className=cls(f.gann.tone);$('gannScore').textContent=signed(f.gann.score);$('gannScore').className=cls(f.gann.tone);$('gannDetail').innerHTML=dl([['摆动',`${fmt(f.gann.swing_low)} — ${fmt(f.gann.swing_high)}`],['八分位',`${f.gann.position_eighth}/8`],['支撑 / 阻力',`${fmt(f.gann.support)} / ${fmt(f.gann.resistance)}`],['1×1线',fmt(f.gann.line_1x1)],['时间窗',f.gann.next_time_window||'暂无临近窗口']])}
function renderDecisions(dec){for(const side of ['long','short']){const x=dec[side],pre=side;$(`${pre}Priority`).textContent=x.priority;$(`${pre}Trigger`).textContent=x.trigger_text;$(`${pre}Detail`).innerHTML=dl([[side==='long'?'回踩入场':'反抽入场',range(x.entry)],['目标 T1 / T2',`${fmt(x.targets[0])} / ${fmt(x.targets[1])}`],['止损 / 失效',`${fmt(x.stop)} · ${x.invalid}`],['每手理论风险',`¥${fmt(dec.risk[`${side}_risk_per_lot`],0)}`]]);$(`${pre}Confirm`).textContent=x.confirmation}}
function renderCandidates(dec){for(const [key,pre] of [['left_long','leftLong'],['left_short','leftShort']]){const x=dec[key];if(!x)continue;$(`${pre}Priority`).textContent=`${x.priority} · ${x.status}`;$(`${pre}Zone`).textContent=range(x.zone);$(`${pre}Trigger`).textContent=x.trigger_text;$(`${pre}Detail`).innerHTML=dl([['失效位',fmt(x.stop)],['目标 T1 / T2',`${fmt(x.targets[0])} / ${fmt(x.targets[1])}`],['每手理论风险',`¥${fmt(x.risk_per_lot,0)}`]])}}
function renderStrategy(){const d=state.detail;if(!d)return;const dec=d.strategies?.[state.strategyFrame]||d.decision;$('strategyHorizon').textContent=`${dec.label||'日线'} · ${dec.horizon||dec.bias}`;$('strategyQuality').textContent=`${dec.bias} · ${dec.quality_note||dec.confidence||'—'}`;renderCandidates(dec);renderDecisions(dec);renderLevels(dec,d.quote.last)}
function renderLevels(dec,price){const vals=[...dec.support,price,...dec.resistance].sort((a,b)=>b-a),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;$('levelMap').innerHTML=vals.map(v=>`<div class="level-item"><span>${v===price?'现价':v>price?'阻力':'支撑'}</span><div class="level-track"><i style="width:${20+80*(v-min)/span}%"></i></div><b class="${v===price?'tone-neutral':''}">${fmt(v)}</b></div>`).join('')}
function renderChart(){const d=state.detail;if(!d)return;const payload=d.charts[state.frame],bars=payload?.bars||[];if(!bars.length){$('priceChart').textContent='暂无K线';return}const W=1100,H=420,P={l:55,r:70,t:18,b:32},pw=W-P.l-P.r,ph=H-P.t-P.b,all=[];bars.forEach(b=>all.push(b.low,b.high));['ma5','ma20','ma60'].forEach(k=>(payload[k]||[]).forEach(v=>v!=null&&all.push(v)));let min=Math.min(...all),max=Math.max(...all),m=(max-min)*.06||1;min-=m;max+=m;const x=i=>P.l+(i+.5)*pw/bars.length,y=v=>P.t+(max-v)*ph/(max-min),cw=Math.max(1,Math.min(7,pw/bars.length*.62));let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<6;i++){const yy=P.t+i*ph/5,val=max-i*(max-min)/5;svg+=`<line x1="${P.l}" y1="${yy}" x2="${W-P.r}" y2="${yy}" stroke="${cssv('--chart-grid','#10272e')}"/><text x="${W-P.r+8}" y="${yy+4}" fill="${cssv('--chart-text','#557078')}" font-size="10">${fmt(val)}</text>`}bars.forEach((b,i)=>{const up=b.close>=b.open,c=up?cssv('--green','#57d6a5'):cssv('--red','#e5676f'),xx=x(i);svg+=`<line x1="${xx}" y1="${y(b.high)}" x2="${xx}" y2="${y(b.low)}" stroke="${c}"/><rect x="${xx-cw/2}" y="${Math.min(y(b.open),y(b.close))}" width="${cw}" height="${Math.max(1,Math.abs(y(b.open)-y(b.close)))}" fill="${c}"/>`});const line=(values,color)=>{let path='',on=false;values.forEach((v,i)=>{if(v==null){on=false;return}path+=`${on?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)} `;on=true});return`<path d="${path}" fill="none" stroke="${color}" stroke-width="1.3"/>`};svg+=line(payload.ma5,cssv('--amber','#dbba6b'))+line(payload.ma20,cssv('--blue','#63a9c4'))+line(payload.ma60,cssv('--violet','#9b86bc'));const step=Math.max(1,Math.floor(bars.length/6));for(let i=0;i<bars.length;i+=step)svg+=`<text x="${x(i)}" y="${H-9}" text-anchor="middle" fill="${cssv('--chart-text','#506a70')}" font-size="9">${String(bars[i].time).slice(5,16)}</text>`;$('priceChart').innerHTML=svg+'</svg>'}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
let installPrompt=null;
function setupPWA(){const install=$('installApp'),standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true,mobile=window.matchMedia('(max-width: 800px)').matches;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('service worker unavailable',e));if(standalone)document.documentElement.classList.add('standalone');else if(mobile)install.classList.remove('hidden');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(!standalone)install.classList.remove('hidden')});install.addEventListener('click',async()=>{if(!installPrompt){toast(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'在 Safari 中点“分享”，再选“添加到主屏幕”':'请用浏览器菜单选择“安装应用”或“添加到主屏幕”');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;install.classList.add('hidden')});window.addEventListener('appinstalled',()=>{installPrompt=null;install.classList.add('hidden');toast('渊行已安装到主屏幕')})}
function renderMacro(e){if(!e)return;$('macroTime').textContent=new Date(e.released_at).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'});$('macroStance').textContent=e.stance;$('macroTitle').textContent=e.title;$('macroVerify').textContent=e.verification;$('macroConclusion').textContent=e.conclusion;$('macroMetrics').innerHTML=e.metrics.map(x=>`<div><span>${x.name}</span><b>${x.actual}</b><small>预期 ${x.consensus} · 前值 ${x.previous}</small></div>`).join('');$('macroTransmission').innerHTML=e.transmission.map(x=>`<p><b>${x.asset} · ${x.view}</b><span>${x.detail}</span></p>`).join('');$('macroNext').innerHTML=e.next.map(x=>`<p><b>${x.time} · ${x.event}</b><span>${x.watch}</span></p>`).join('');$('macroSources').innerHTML=e.sources.map(x=>`<a href="${x.url}" target="_blank" rel="noopener">${x.name} ↗</a>`).join('')}
async function loadMacro(){try{renderMacro((await fetchJSON(`data/macro.json?t=${Date.now()}`)).event)}catch(e){console.warn('macro unavailable',e)}}
let booted=false;function boot(){if(booted)return;booted=true;initTheme();loadMacro();init();window.setInterval(refreshLive,30000)}setupPWA();window.addEventListener('yafco:authorized',boot);if(window.YAFCOAccess?.allowed())boot();
